<div class="footer">
    <div class="footer__list">
        <a href="index.php?page=accueil">Accueil</a>
        <a href="index.php?page=CGV">Termes et conditions</a>
        <a href="index.php?page=cookies">Politique de confidentialité</a>
        <a href="index.php?page=contact">Me contacter</a>
    </div>
   <div class="footer__copyright">
       <p >Copyright © <?= date('Y') ?> @ <?= TITRE ?></p>
   </div>
</div>

