<div class="navbar">
    <div for="navToggle" class="navbar__button display">
        <span class="nav__burger"><i class="fa-solid fa-bars"></i></span>
    </div>

    <div class="navbar__menu display">
        <ul class="navbar__list">
            <li><a class="navbar__link" href="index.php?page=accueil">Accueil</a></li>
            <li><a class="navbar__link" href="index.php?page=programme">Programme</a></li>
            <li><a class="navbar__link" href="index.php?page=poids">Poids</a></li>
            <li><a class="navbar__link" href="index.php?page=Blog">Blog</a></li>
            <li><a class="navbar__link" href="index.php?page=Contact">Me contacter</a></li>
        </ul>
    </div>
</div>

