<div class="navbar">
    <div for="navToggle" class="navbar__button">
        <span class="navbar__burger appear"><i class="fa-solid fa-bars "></i></span>
    </div>

    <div class="navbar__menu display">
        <ul class="navbar__list">
            <li><a class="navbar__link" href="index.php?page=accueil">Accueil</a></li>
            <li><a class="navbar__link" href="index.php?page=programme">Programme</a></li>
            <li><a class="navbar__link" href="index.php?page=poids">Poids</a></li>
            <li><a class="navbar__link" href="index.php?page=guide">Guide des exercices</a></li>
            <li><a class="navbar__link" href="index.php?page=contact">Me contacter</a></li>
        </ul>
    </div>
</div>

