<div class="headPage">
    <div class="logoSite"><img src="public/medias/logoGymrat.png" alt="logo"></div>
    <div class="titre"><p id="titre">Gymrat Programme</p></div>
    <div class="iconLogHead">
        <div><a href="index.php?page=profil"><i class="fa-solid fa-user-plus"></i></a></div>
        <div><a href="index.php?page=contact"><i class="fa-solid fa-envelope"></i></a></div>
    </div>

</div>
