<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Gymrat Programme</title>
<link rel="stylesheet" href="public/styles/css/style.css" type="text/css" />
<link rel="shortcut icon" type="image/png" href="public/medias/faviconDB.png"/>
<script src="https://kit.fontawesome.com/4676f47122.js" crossorigin="anonymous"></script>
