<div class="userProfil">
    <div class="userProfil__btn">
            <h2 class="userProfil__userName"><i class="fa-solid fa-user"></i><span class="underline"> <?= $_SESSION['login'] ?></span></h2>
    </div>
    <div class="userProfil__menu hide">
        <ul class="userProfil__list">
            <li><a href="index.php?page=user&action=logout"><i class="fa-solid fa-right-from-bracket"></i> Déconnecte-toi</a></li>
            <li><a href="index.php?page=client&action=update"><i class="fa-solid fa-pen-to-square"></i> Modifie-toi</a></li>
            <li><a href="index.php?page=client&action=delete"><i class="fa-solid fa-trash"></i> Supprime-toi</a></li>
            <i class="fa-solid fa-circle-xmark" id="closeBtn"></i>
        </ul>

    </div>
</div>

