<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <nav>
        <?php require_once "includes/partials/navbar.phtml"; ?>
    </nav>

    <section class="titleH1">
        <div class="top">Accueil</div>
        <div class="bottom" aria-hidden="true">Accueil</div>
    </section>
    <div>
        <h2>Bonjour <?= $_SESSION['login'] ?></h2>
    </div>
    <!-- PROGRAMME ------------------>
    <article>
        <p>Ton programme de gymrat:</p>
        <div>
            <?php
                if($unClient->getProgramme()!= null){
                    print('<p>'.$unClient->getProgramme()->getLibelle().'</p>');
                    print('<p>'.$unClient->getProgramme()->getFrequence().' <span>jours</span></p>');
                    print('<p>'.$unClient->getProgramme()->getDescription().'</p>');
                }else{
                    print('<p>Trouver un programme</p>');
                    print('<a class="buttonAdd" href="index.php?page=programme"><i class="fa-solid fa-dumbbell"></i></a>');
                }
            ?>
        </div>
    </article>
    <footer>
        <?php
            require_once "includes/partials/userMenu.phtml";
            ?>
    </footer>
</main>
<footer>
    <?php require_once "includes/partials/footer.phtml"; ?>
</footer>
<script src="public/scripts/scriptMenu.js"></script>
</body>
</html>