<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <nav>
        <?php require_once "includes/partials/navbar.phtml"; ?>
    </nav>
    <section class="title">
        <div class="main-title">
            <div class="top">Accueil</div>
            <div class="bottom" aria-hidden="true">Accueil</div>
        </div>
        <h2>Bonjour <span class="underline"><?= $_SESSION['login'] ?></span></h2>
    </section>

<div class="home">
    <div class="home__container">
        <div class="home__cards">
<!---------------SECTION  PROGRAMME ------------------>
    <section class="home__programme card">
        <div class="icon"><i class="fa-solid fa-list-ul"></i></div>
        <h3 class="subTitle">Le programme de gymrat que t'as choisi: </h3>
        <div class="text">
            <?php
                    print('<p>'.$unClient->getProgramme()->getLibelle().'</p>');
                    print('<p>'.$unClient->getProgramme()->getDescription().'</p>');
            ?>
        </div>
        <div class="btn">
        <?php
            print("<a href=\"index.php?page=programme#{$unClient->getProgramme()->getId()}\"> Afficher le programme </a>");
        ?>
        </div>
        <div class="btn">
            <a href="index.php?page=programme"><i class="fa-solid fa-dumbbell"></i>Tous les programmes</a>
        </div>
    </section>
<!----------------- SECTION DAYS--------------->
        <section class="home__days card">
            <div class="icon"><i class="fa-solid fa-retweet"></i></div>
            <h3 class="subTitle">Prêt pour s'entrainer</h3>
            <div class="text">
            <?php
                    print('<p><span>'.$unClient->getProgramme()->getFrequence().' jours</span></p>');
            ?>
            </div>
        </section>
<!----------------- SECTION POIDS--------------->
    <section class="home_weight card">
        <div class="icon"><i class="fa-solid fa-weight-scale"></i></div>
        <h3 class="subTitle">Ton poids ça donne ça: </h3>
        <div class="text">
        <?php

        print('<p id="home__weightStart">Ton poids de référence:<span> '.$unClient->getPoidsRef().' kg</span></p>');
        print('<p id="home__weightNow">Ton poids actuel:<span>  '.$unPoids->getValeur().' kg</span></p>');
        print('<p id="home__weightGoal">Ton objectif de poids:<span>  '.$unClient->getPoidsVise().' kg</span></p>');
        print('<p id="home__weightLeft">Il te reste <span> '.($unPoids->getValeur()) - ($unClient->getPoidsVise()).'kg</span> avant ton objectif</p>');

        ?>
        </div>
        <div class="btn">
            <a href="index.php?page=poids"><i class="fa-solid fa-dumbbell"></i>Ta courbe de poids</a>
        </div>
    </section>
    </div>
    <footer>
        <?php
            require_once "includes/partials/userMenu.phtml";
            require_once "includes/partials/back_to_the_top.phtml";
            ?>
    </footer>
    </div>
</div>
</main>
<footer>
    <?php require_once "includes/partials/footer.phtml"; ?>
</footer>
<script src="public/scripts/scriptMenu.js"></script>
</body>
</html>