<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <?php require "includes/partials/navbar.phtml"; ?>
    <section class="title">
        <div class="main-title">
            <div class="top">POLITIQUE DE CONFIDENTIALITÉ</div>
            <div class="bottom" aria-hidden="true">POLITIQUE DE CONFIDENTIALITÉ</div>
        </div>
        <h2>POLITIQUE DE <span class="underline">CONFIDENTIALITÉ</span></h2>
    </section>
    <section class="cookies">
        <h1>POLITIQUE DE CONFIDENTIALITÉ</h1>
        <p>
            Cette politique de confidentialité s’applique au site : GYMRAT PROGRAMME.
            La présente politique de confidentialité a pour but d’exposer aux utilisateurs du site :
            La manière dont sont collectées et traitées leurs données à caractère personnel. Doivent être considérées comme données personnelles toutes les données étant susceptibles d’identifier un utilisateur. Il s’agit notamment du prénom et du nom, de l’âge, de l’adresse postale, l’adresse mail, la localisation de l’utilisateur ou encore son adresse IP ;
            Quels sont les droits des utilisateurs concernant ces données ;
            Qui est responsable du traitement des données à caractère personnel collectées et traitées ;
            A qui ces données sont transmises ;
            La politique du site en matière de fichiers « cookies ».
        </p>

        <h4>Propriété intellectuelle et droits d’auteur</h4>
        <p>Tous les contenus (textes, photos, vidéos, ebooks, guides, programmes) et tous les autres éléments composant le site sont la propriété exclusive de GYMRAT PROGRAMME.
            Toute représentation, reproduction, et/ou exploitation, qu’elle soit partielle ou totale, est interdite, sauf accord écrit et préalable de GYMRAT PROGRAMME .
        </p>


        <h4>COLLECTE ET DE TRAITEMENT DE DONNÉES</h4>
        <p>Conformément aux dispositions de l’article 5 du Règlement européen 2016/679, la collecte et le traitement des données des utilisateurs du site respectent les principes suivants :
            Licéité, loyauté et transparence : les données ne peuvent être collectées et traitées qu’avec le consentement de l’utilisateur propriétaire des données. A chaque fois que des données à caractère personnel seront collectées, il sera indiqué à l’utilisateur que ses données sont collectées, et pour quelles raisons ses données sont collectées ;
            Finalités limitées : la collecte et le traitement des données sont exécutés pour répondre à un ou plusieurs objectifs déterminés dans les présentes conditions générales d’utilisation ;
            Minimisation de la collecte et du traitement des données : seules les données nécessaires à la bonne exécution des objectifs poursuivis par le site sont collectées ;
            Conservation des données réduites dans le temps : les données sont conservées pour une durée limitée, dont l’utilisateur est informé. Lorsque cette information ne peut pas être communiquée, l’utilisateur est informé des critères utilisés pour déterminer la durée de conservation ;
            Intégrité et confidentialité des données collectées et traitées : le responsable du traitement des données s’engage à garantir l’intégrité et la confidentialité des données collectées.
            Afin d’être licites, et ce conformément aux exigences de l’article 6 du règlement européen 2016/679, la collecte et le traitement des données à caractère personnel ne pourront intervenir que s’ils respectent au moins l’une des conditions ci-après énumérées :
            responsable du traitement ou par un tiers.
        </p>

        <h4>COLLECTE ET TRAITEMENT DES DONNÉES</h4>
        <p>Données collectées et traitées et mode de collecte
            Les données à caractère personnel collectées sur le site GYMRAT PROGRAMME  sont les suivantes :
            Nom / prénom
            Adresse mail
            Ces données sont collectées lorsque l’utilisateur effectue l’une des opérations suivantes sur le site :
            Envoyer un message à hugonmauranepro@gmail.com via le formulaire de contact du site (nom, prénom, adresse email)
            Le responsable du traitement conservera dans ses systèmes informatiques du site et dans des conditions raisonnables de sécurité l’ensemble des données collectées pour une durée de 3 ans.
            La collecte et le traitement des données répondent aux finalités suivantes :
            Répondre aux demandes envoyées auprès de hugonmauranepro@gmail.com
            Transmissions des données à des tiers
            Les données à caractère personnel collectées par le site ne sont traitées que par l’éditeur du Site.
        </p>

        <h4>RESPONSABLE DU TRAITEMENT DES DONNÉES</h4>

        <p>Le responsable du traitement des données
            La responsable du traitement des données à caractère personnel est HUGON Maurane. Ils peuvent être contacté par email à hugonmauranepro@gmail.com
            Le responsable du traitement des données est chargé de déterminer les finalités et les moyens mis au service du traitement des données à caractère personnel.
            Obligations du responsable du traitement des données
            Le responsable du traitement s’engage à protéger les données à caractère personnel collectées, à ne pas les transmettre à des tiers sans que l’utilisateur n’en ait été informé et à respecter les finalités pour lesquelles ces données ont été collectées.
            Le site dispose d’un certificat SSL afin de garantir que les informations et le transfert des données transitant par le site sont sécurisés.
            Un certificat SSL (« Secure Socket Layer » Certificate) a pour but de sécuriser les données échangées entre l’utilisateur et le site.
            De plus, le responsable du traitement des données s’engage à notifier l’utilisateur en cas de rectification ou de suppression des données, à moins que cela n’entraîne pour lui des formalités, coûts et démarches disproportionnés.
            Dans le cas où l’intégrité, la confidentialité ou la sécurité des données à caractère personnel de l’utilisateur est compromise, le responsable du traitement s’engage à informer l’utilisateur par tout moyen.
        </p>

        <h4>DROITS DE L’UTILISATEUR</h4>

        <p>Conformément à la réglementation concernant le traitement des données à caractère personnel, l’utilisateur possède les droits ci-après énumérés :
            Droit d’accès, de rectification et droit à l’effacement : L’utilisateur peut prendre connaissance, mettre à jour, modifier ou demander la suppression des données le concernant, en respectant la procédure ci-après énoncée ;
            Droit à la portabilité des données : L’utilisateur a le droit de demander la portabilité de ses données personnelles, détenues par le site, vers un autre site ;
            Droit à la limitation et à l’opposition du traitement des données
            L’utilisateur a le droit de demander la limitation ou de s’opposer au traitement de ses données par le site, sans que le site ne puisse refuser, sauf à démontrer l’existence de motifs légitimes et impérieux, pouvant prévaloir sur les intérêts et les droits et libertés de l’utilisateur ;
            Droit de déterminer le sort des données après la mort
            Il est rappelé à l’utilisateur qu’il peut organiser quel doit être le devenir de ses données collectées et traitées s’il décède, conformément à la loi n°2016-1321 du 7 octobre 2016.
            L’utilisateur doit envoyer sa demande par email à hugonmauranepro@gmail.com
            Afin que le responsable du traitement des données fasse droit à sa demande, l’utilisateur est tenu de lui communiquer : ses prénom et nom ainsi que son adresse e-mail, ainsi que la photocopie d’un titre d’identité en cours.
            Le responsable du traitement des données est tenu de répondre à l’utilisateur dans un délai de trente jours maximum.
        </p>

        <h4>UTILISATION DES FICHIERS « COOKIES »</h4>

        <p>Le site GYMRAT PROGRAMME peut être amené à vous demander l’acceptation des cookies pour des besoins de statistiques et d’affichage.
            Un cookie est une information déposée sur votre disque dur par le serveur du site que vous visitez. Il contient plusieurs données qui sont stockées sur votre ordinateur dans un simple fichier texte auquel un serveur accède pour lire et enregistrer des informations. Certaines parties de ce site ne peuvent être fonctionnelles sans l’acceptation de cookies.
            Il est porté à la connaissance de l’utilisateur qu’il peut s’opposer à l’enregistrement de ces fichiers « cookies » en configurant son logiciel de navigation.
            Dans le cas où l’utilisateur décide de désactiver les fichiers « cookies », il pourra poursuivre sa navigation sur le site. Toutefois, tout dysfonctionnement du site provoqué par cette manipulation ne pourrait être considéré comme étant du fait de l’éditeur du site.
            En naviguant sur le site, il est porté à connaissance de l’utilisateur que des fichiers « cookies » de tiers peuvent être enregistrés.
            Il s’agit plus particulièrement des tiers suivants : Google Analytics.
            De plus, le site intègre des boutons de réseaux sociaux, permettant à l’utilisateur de partager son activité sur le site. Des fichiers « cookies » de ces réseaux sociaux sont par conséquent susceptibles d’être stockés sur l’ordinateur de l’utilisateur lorsqu’il utilise ces fonctionnalités.
            L’attention de l’utilisateur est portée sur le fait que ces sites disposent de politiques de confidentialité propres et de conditions générales d’utilisation possiblement différentes du site. L’éditeur du site invite les utilisateurs à consulter les politiques de confidentialité et les conditions générales d’utilisation de ces sites.

        <h4>MODIFICATION DE LA POLITIQUE DE CONFIDENTIALITÉ</h4>

        <p>L’éditeur du site se réserve le droit de la modifier afin de garantir sa conformité avec le droit en vigueur.
            Par conséquent, l’utilisateur est invité à venir consulter régulièrement cette politique de confidentialité afin de se tenir informé des derniers changements qui lui seront apportés.
            Il est porté à la connaissance de l’utilisateur que la dernière mise à jour de la présente politique de confidentialité est intervenue le 07/04/2023.
        </p>

    </section>
    <?= $message ?? '' ?>
</main>
<footer>
    <?php
        require_once "includes/partials/footer.phtml";
    ?>
</footer>
</body>
<?php require_once "includes/partials/footer.phtml"; ?>
</html>
