<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>

    <!--------------- CONNECTION ---------------------------->
    <article class="connectForm">
        <form action="" method="post" enctype="multipart/form-data">
            <div class="connectForm__cont">
                <header class="connectForm__head">
                    <h1>Se connecter</h1>
                    <p>Connecte toi ici avec ton nom d'utilisateur et ton mot de passe.</p>
                </header>
                <div class="connectForm__field">
                    <!------  User ------->
                    <div class="connectForm__user">
                    <span class="connectForm__inputItem">
                        <i class="fa fa-user-circle"></i>
                    </span>
                    <input
                        name="login"
                        id="login"
                        type="text"
                        placeholder="Nom d'utilisateur"
                        required
                    />
                    </div>

                    <!-------   Password -------->
                    <div class="connectForm__mdp">
                    <span class="connectForm__inputItem">
                         <i class="fa fa-key"></i>
                     </span>
                    <input
                        name="mdp"
                        type="password"
                        placeholder="Mot de passe"
                        id="mdp"
                        required
                    />
                    <!-- Show/hide password  -->
                    <span>
                     <i class="fa fa-eye" id="eye"></i>
                    </span>
                    </div>

                </div>
                <div class="connectForm__btns">
                    <!-- button LogIn -->
                    <button class="btn submits logIn" type="submit">Se connecter</button>

                    <!-- Sign Up button -->
                    <a href="index.php?page=client&action=add">
                        <button class="btn submits signUp" type="button">
                            S'inscrire
                            <i class="fa fa-user-plus"></i>
                        </button>
                    </a>
                </div>
            </div>
        </form>
    </article>
    <?= $message ?? '' ?>
</main>
<footer>
    <?php
        require_once "includes/partials/footer.phtml";
    ?>
</footer>
</body>
<?php require_once "includes/partials/footer.phtml"; ?>
</html>
