<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <section class="title">
        <div class="main-title">
            <div class="top">Inscription Gymrat</div>
            <div class="bottom" aria-hidden="true">Inscription Gymrat</div>
        </div>
            <h2>Fiche du <span class="underline">gymrat</span></h2>
    </section>
    <!--------------- INSCRIPTION ---------------------------->

    <form action="" method="post" enctype="multipart/form-data">
        <div class="newcontact__form">
        <div>
            <label for="genre">Genre</label>
            <select name="genre" id="genre">
                <option value="0">-- Sélectionner --</option>
                <?php
                    foreach ($lesGenres as $unGenre){
                        if($unGenre->getId() == $unClient->getGenre()->getId()){
                            print('<option value="'.$unGenre->getId().'" selected>'.$unGenre->getLibelleLong().'</option>');
                        }else{
                            print('<option value="'.$unGenre->getId().'">'.$unGenre->getLibelleLong().'</option>');
                        }

                    }
                ?>
            </select>
        </div>
        <div>
            <label for="nom">Nom : <span class="required">*</span> </label><input type="text" name="nom" id="nom" value="<?= $unClient->getNom() ?>" required>
        </div>
        <div>
            <label for="prenom">Prénom : <span class="required">*</span> </label><input type="text" name="prenom" id="prenom" value="<?= $unClient->getPrenom() ?>" required>
        </div>
        <div>
            <label for="dateNaissance">Date de naissance : <span class="required">*</span> </label><input type="date" name="dateNaissance" id="dateNaissance" value="<?= $unClient->getDateNaissance()->format('Y-m-d') ?>" required>
        </div>
        <div>
            <label for="poidsRef">Poids de référence: <span class="required">*</span> </label>
            <input type="number" name="poidsRef" id="poidsRef" value="<?= $unClient->getPoidsRef() ?>" required min="20" max="200">
        </div>
        <div>
            <label for="poidsVise">Objectif de poids final: <span class="required">*</span> </label>
            <input type="number" name="poidsVise" id="poidsVise" value="<?= $unClient->getPoidsVise() ?>" required min="20" max="200">
        </div>
        <div>
            <label for="taille">Taille : <span class="required">*</span> </label>
            <input type="number" name="taille" id="taille" value="<?= $unClient->getTaille() ?>" required min="100" max="250">
        </div>
        <div>
            <label for="email">E-mail : <span class="required">*</span> </label><input type="email" name="email" id="email" value="<?= $unClient->getEmail() ?>" required>
        </div>
        <div>
            <label for="telephone">Téléphone : <span class="required">*</span> </label><input type="tel" name="telephone" id="telephone" value="<?= $unClient->getTel() ?>" required>
        </div>

        <div>
            <label for="Ville">Ville : <span class="required">*</span> </label><input type="ville" name="ville" id="ville" value="<?= $unClient->getVille() ?>" required>
        </div>
        <div>
            <label for="login">Nom d'utilisateur : <span class="required">*</span> </label><input type="login" name="login" id="login" value="<?= $unClient->getUser()->getLogin() ?>" required>
        </div>
            <span class="required"><?= $messageLog ?? '' ?></span>
        <div>
            <label for="mdp">Mot de passe : <span class="required">*</span> </label><input type="password" name="mdp" id="mdp" required>
        </div>
            <div>
                <label for="mdp">Confirmer le mot de passe : <span class="required">*</span> </label><input type="password" name="mdpConfirm" id="mdpConfirm" required>
            </div>
            <span class="required"><?= $messageMdp ?? '' ?></span>

        <div class="cont_btn">
            <button class="btn" type="submit">Valider</button>
            <button class="btn"  type="reset">Réinitialiser</button>
        </div>
        </div>
    </form>

    <?= $message ?? '' ?>
</main>
<script src="public/scripts/scriptMenu.js"></script>
</body>
</html>
