<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <?php require "includes/partials/navbar.phtml"; ?>
    <section class="title">
        <div class="main-title">
            <div class="top">Contacte-nous</div>
            <div class="bottom" aria-hidden="true">Contacte-nous</div>
        </div>
            <h2>Dis-nous <span class="underline">tout</span></h2>
    </section>
    <!--------------- CONTACT ---------------------------->
    <article class="contact">
        <form class="contact__form" action="" method="POST" enctype="multipart/form-data">
            <div class="contact__input">
            <label for="nom">Nom :</label>
            <input type="text" id="nom" name="nom" required>
            </div>

            <div class="contact__input">
            <label for="prenom">Prénom :</label>
            <input type="text" id="prenom" name="prenom" required>
            </div>

            <div class="contact__input">
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" required>
            </div>

            <div class="contact__input">
            <label for="message">Message :</label>
            <textarea id="message" name="message" required></textarea>
            </div>

            <div class="contact__input">
            <button class="btn" type="submit">Envoyer</button>
            </div>

        </form>
    </article>
    <?= $message ?? '' ?>
</main>
<footer>
    <?php
        require_once "includes/partials/footer.phtml";
    ?>
</footer>
</body>
</html>
