<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <?php require "includes/partials/navbar.phtml"; ?>

    <section class="title">
        <div class="main-title">
            <div class="top">Nouveau poids</div>
            <div class="bottom" aria-hidden="true">Nouveau poids</div>
        </div>
            <h2>Ajoute un <span class="underline">poids</span></h2>
    </section>

    <!--------------- ajout du nouveau poids ---------------------------->
    <form class="formPoids" action="" method="post" enctype="multipart/form-data">
        <div class="formPoids__label">
            <label for="dateAjout">Date d'ajout du poids: </label><input type="date" name="dateAjout" id="dateAjout" value="<?= $unPoids->getDateAjout()->format('Y-m-d') ?>">
            <label for="valeur">Nouveau poids : </label><input type="number" step="any" name="valeur" id="valeur" value="">
        </div>
        <div class="formPoids__btns">
            <button class="btn" type="submit">Valider</button>
            <a class="btn" href="index.php?page=poids">Retour</a>
        </div>
    </form>
    <?= $message ?? '' ?>
</main>
<footer>
    <?php
        require_once "includes/partials/footer.phtml";
    ?>
</footer>
<script src="public/scripts/scriptMenu.js"></script>
</body>
</html>
