<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>

    <!--------------- INSCRIPTION ---------------------------->
    <form action="" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Nouveau programme 🔱</legend>
            <div>
                <label for="jours">Jours</label>
                <select name="jours" id="jours">
                    <option value="0">-- Sélectionner --</option>
                    <?php
                        foreach ($lesJours as $unJour){
                            if($unJour->getId() == $uneSession->getJours()->getId()){
                                print('<option value="'.$unJour->getId().'" selected>'.$unJour->getLibelleLong().'</option>');
                            }else{
                                print('<option value="'.$unJour->getId().'">'.$unJour->getLibelle().'</option>');
                            }

                        }
                    ?>
                </select>
            </div>
            <div>
                <label for="session">Session</label>
                <select name="session" id="session">
                    <option value="0">-- Sélectionner --</option>
                    <?php
                        foreach ($lesSessions as $uneSession){
                                print('<option value="'.$uneSession->getId().'" selected>'.$uneSession->getLibelle().'</option>');
                        }
                    ?>
                </select>
            </div>
                <div>
                    <label for="exercice">Exercice : </label><input type="text" name="prenom" id="prenom">
                </div>
                <div>
                    <label for="nbre_serie">Nombre série : </label><input type="number" name="nbre_serie" id="nbre_serie">
                </div>
                <div>
                    <label for="nbre_rep">Nombre de répétition: </label>
                    <input type="number" name="nbre_rep" id="nbre_rep">
                </div>

                <div>
                    <label for="poids">Poids / Charge : </label><input type="number" name="poids" id="poids">
                </div>
                <div>
                    <button type="submit">Ajouter sess'</button>
                    <button type="button">Annuler</button>
                </div>
        </fieldset>
    </form>
    <?= $message ?? '' ?>
</main>
<footer>
    <?php
        require_once "includes/partials/footer.phtml";
    ?>
</footer>
</body>
</html>
