<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <nav>
        <?php require_once "includes/partials/navbar.phtml"; ?>
    </nav>
     <section class="title">
            <div class="main-title">
                <div class="top">Guide des exercices</div>
                <div class="bottom" aria-hidden="true">Guide des exercices</div>
            </div>
                <h2>Guide des <span class="underline">exercices</span></h2>
    </section>

    <section class="guideExercices">
        <div class="guideExercices__container">
        <form class="formGuide" action="" method="post" enctype="multipart/form-data">
            <div class="formGuide__select">
                <label class="subTitle" for="exercices">Liste des exercices: </label>
                <select name="exercices" id="exercices">
                    <option value="0">-- Sélectionner --</option>
                    <?php
                        foreach ($lesExercices as $unExercice) {
                            print('<option value="'.$unExercice->getId().'">'.$unExercice.'</option>');
                        }
                    ?>
                </select>
            </div>
            <div class="formGuide__media" id="infosExercices">
            <!-- video injectée via la BDD voir script guideExercices.js -->
            </div>
        </form>
        </div>
    </section>
    <footer>
        <?php
            require_once "includes/partials/footer.phtml";
            require_once "includes/partials/userMenu.phtml";
        ?>
    </footer>
</main>
<?php
    require_once "includes/partials/scripts.phtml";
?>
</body>
</html>