<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>

<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>

<main>
    <?php require "includes/partials/navbar.phtml"; ?>

    <section class="title">
        <div class="main-title">
            <div class="top">Ton poids</div>
            <div class="bottom" aria-hidden="true">Ton poids</div>
        </div>
            <h2>Tu pèses <span class="underline">combien</span> ?</h2>
    </section>
<section class="poids">
    <div class="poids__views">
        <div class="poids__start">
            <?php
                print('<p> Ton poids de départ est: </p>');
                print('<span>'.$unClient->getPoidsRef().' kg</span>');
            ?>
        </div>
        <div class="poids__now">
            <?php
                print('<p>Ton poids actuel:</p>');
                if($unPoids->getValeur() > $unClient->getPoidsRef())
                {
                    print('<span class="required">'.$unPoids->getValeur().' kg</span>');
                }else{
                    print('<span>'.$unPoids->getValeur().' kg</span>');
                }

            ?>
        </div>
        <div class="poids__goal">
            <?php
                print('<p>Ton objectif de poids: </p>');
                print('<span>'.$unClient->getPoidsVise().' kg</span>');
            ?>
        </div>
    </div>
    <div class="poids__add">
        <a class="btn" href="index.php?page=poids&action=add">Ajouter un poids <i class="fa-solid fa-plus"></i></a>
    </div>

    <div class="liste__poids">
        <?php
            $tableauPoidsJS = 'let poids = [';
            $tableauDatesJS = 'let dates = [';
            //var_dump($lesPoids);
            foreach ($lesPoids as $unPoids){
                if($unPoids->getValeur()){
                    $unPoids->getValeur();
                    $unPoids->getDateAjout()->format('d-m-Y');

                    //Pour tests
                    $tableauPoidsJS .= $unPoids->getValeur().',';
                    $tableauDatesJS .= '\''.$unPoids->getDateAjout()->format('d-m-y').'\',';
                }
            }

            $tableauPoidsJS = substr($tableauPoidsJS, 0, strlen($tableauPoidsJS) - 1).'];';
            $tableauDatesJS = substr($tableauDatesJS, 0, strlen($tableauDatesJS) - 1).'];';
        ?>
    </div>

<!----------------------GRAPH CANVAS--------------------------->
    <div class="graph_container">
        <canvas id="graphCanvas" aria-label="chart" role="img"></canvas>
    </div>
</section>
</main>
<footer>
    <?php require_once "includes/partials/footer.phtml"; ?>
</footer>

<!----------------------LIEN ENTRE JS ET PHP--------------------------->
<script>
    <?= $tableauPoidsJS ?>
    <?= $tableauDatesJS ?>
</script>
<?php
    require_once "includes/partials/scripts.phtml";
?>
</body>
</html>
