<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <nav>
        <?php require_once "includes/partials/navbar.phtml"; ?>
    </nav>
    <section class="title">
        <h1>
            <div class="top">Les programmes</div>
            <div class="bottom" aria-hidden="true">Les programmes</div>
        </h1>
    </section>
    <h2>Choisir un programme</h2>
    <table>
        <thead>
        <th>Programme: </th>
        </thead>
        <tbody>
        <?php

            foreach ($lesProgrammes as $unProgramme){
                print('<tr>');
                print('<td>'.$unProgramme->getLibelle().'</td>');
                print('<td>'.$unProgramme->getFrequence().' <span>jours</span></td>');
                print("<td><a href=\"#{$unProgramme->getId()}\">Afficher</a></td>");
                print("<td><a href=\"index.php?page=client&action=setProg&id={$unProgramme->getId()}\">Choisir</a></td>");
                print('</tr>');
            }
        ?>
        </tbody>
    </table>
<article class="fiche">
    <?php
        foreach ($lesProgrammes as $unProgramme){
            print('<div class="ficheProg">');
            print('<h2 class="__title" id='.$unProgramme->getId().'>'.$unProgramme->getLibelle().'</h2>');
            print('<p class="__frequence">'.$unProgramme->getFrequence().' <span>jours</span></p>');
            print('<p class="__description">'.$unProgramme->getDescription().'</p>');
            print('</div>');
            foreach ($unProgramme->getSessions() as $uneSession){
                print('<div class="ficheSessions">');
                print('<p class="__libelle">'.$uneSession->getLibelle().'</p>');
                print('</div>');
                foreach ($uneSession->getExercices() as $unExercice){
                    print('<div class="ficheExo">');
                    print('<p class="__nom">'.$unExercice.'</p>');
                    print('<p class="__serie">Nombre de série: '.$unExercice->getNbreSerie().'</p>');
                    print('<p class="__rep">Nombre de répétitions: '.$unExercice->getNbreRep().'</p>');
                    print('<p class="__pause">Temps de pause entre chaque série: '.$unExercice->getPAuse().'</p>');
                    print('</div>');
                }
            }
            print("<a href=\"index.php?page=client&action=setProg&id={$unProgramme->getId()}\">Choisir</a>");
            print('<br>');

        }
    ?>
</article>
    <footer>
        <?php
            require_once "includes/partials/userMenu.phtml";
        ?>
    </footer>
</main>
<footer>
    <?php require_once "includes/partials/footer.phtml"; ?>
</footer>
<script src="public/scripts/scriptMenu.js"></script>
</body>
</html>