<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <nav>
        <?php require_once "includes/partials/navbar.phtml"; ?>
    </nav>
    <header>
        <h1> PROGRAMME DU GYMRAT</h1>
    </header>
    <h2>Choisir un programme</h2>
    <table>
        <thead>
        <th>Programme: </th>
        </thead>
        <tbody>
        <?php
            foreach ($lesProgrammes as $unProgramme){
                print('<tr>');
                print('<td>'.$unProgramme->getLibelle().'</td>');
                print('<td>'.$unProgramme->getFrequence().' <span>jours</span></td>');
                print("<td><a href=\"#{$unProgramme->getId()}\">Afficher</a></td>");
                print("<td><a href=\"index.php?page=client&action=setProg&id={$unProgramme->getId()}\">Choisir</a></td>");
                print('</tr>');
            }
        ?>
        </tbody>
    </table>
<article class="ficheProg">
    <?php
        foreach ($lesProgrammes as $unProgramme){
            print('<br>');
            print('<h2 class="ficheProg__title" id='.$unProgramme->getId().'>'.$unProgramme->getLibelle().'</h2>');
            print('<p class="ficheProg__frequence">'.$unProgramme->getFrequence().' <span>jours</span></p>');
            print('<p class="ficheProg__description">'.$unProgramme->getDescription().'</p>');
            print("<a href=\"index.php?page=client&action=setProg&id={$unProgramme->getId()}\">Choisir</a>");
            print('<br>');
        }
    ?>
</article>
    <footer>
        <?php require_once "includes/partials/footer.phtml"; ?>
    </footer>
</main>
</body>
</html>