<?php
    ini_set('display_errors', 'on');
    require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
<header>
    <?php require "includes/partials/page_header.phtml"; ?>
</header>
<main>
    <section class="titleH1">
        <div class="top">Bienvenue</div>
        <div class="bottom" aria-hidden="true">Bienvenue</div>
    </section>

    <!--------------- CONNECTION ---------------------------->
    <article class="logSignForm">
        <form action="" method="post" enctype="multipart/form-data">
            <div class="cont_btn">
                <a href="index.php?page=user&action=login">
                    <button class="btn login frgtPass" type="button">Se connecter</button>
                </a>
                <a href="index.php?page=client&action=add">
                    <button class="btn signup frgtPass" type="button">S'inscrire</button>
                </a>
            </div>
        </form>
    </article>
</main>
<footer>
    <?php
        require_once "includes/partials/footer.phtml";
    ?>
</footer>
</body>
</html>
